<div class="container">
    <div class="row">
        <h2><?php $this->getPageTitle();?></h2>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1 class="h1 text-center">MV Framework</h1>
            <p>Este é um micro framework MVC em PHP, construído como exercício do conteúdo didático do curso "Micro Framework do Zero" disponibilizado no canal TJG Web no Youtube.</p>
        
        </div>

    </div>
</div>